= Protokoll Gruppe 2

Treffen am 11.04.2023

Ort:      BigBlueButton +
Beginn:   15:15 Uhr +
Ende:     15:54 Uhr

__Schriftführer:__ Leon Kunze

*Nächstes Treffen:* +
13.04.2023, 11:00 Uhr, Hg/G/-1/19

__Teilnehmer:__
- Astrid Rindfleisch
- Duc Hieu Le
- Leon Kunze
- Andrii Roshkovan
- Prof. Dr. Ronny Weinkauf

== Bemerkungen
- Das treffen wurde aufgezeichnet (wird noch nachgetragen)

== Retrospektive des letzten Sprints
- Jedes Teammitglied sollte sich mit den zur verfügung gestellten Dokumenten vertraut machen
- ggf. Fragen stellen falls etwas nicht klar ist 


== Aktueller Stand
- es soll keine externe/spezielle Bibliothek verwendet, damit keine Lizenzen verletzt werden sollte das Projekt veröffentlicht werden
- GitHub kann selber erstellt werden oder wir erstellen zum nächsten Termin ein Repository mit Prof. Weinkauf
    - das Repository wird somit öffentlich sein
- das von uns erstellte Tool sammelt quantitativ Daten, welche am Ende mit der Fachliteratur verglichen werden soll

== Planung des nächsten Sprints

